### ISSUE TITLE
Problems when writing/ editing query files

### ISSUE THREAD

**Issue by nedykes** [ausgerechnet/spheroscope#45]
Queries edited or newly created via the app are currently not being written to the local instance folder.
Queries deleted from the local instance still show up in the app (but then can't be deleted from there because it says that the file no longer exists)

**Comment by ausgerechnet** [comment]
- created queries will now actually show in the interface
- the delete button is now working but (1) I had to remove the "confirm" pop-up and (2) I don't know why it doesn't redirect back to the index

**Comment by ausgerechnet** [comment]
@mgttlinger maybe you can have a quick look; I guess the same problem arises with the delete button for macros and wordlists

**Comment by mgttlinger** [comment]
> * the delete button is now working but (1) I had to remove the "confirm" pop-up and (2) I don't know why it doesn't redirect back to the index

It doesn't redirect anymore because you switched from a form submit button to an asynchronous button that just triggers the request without redirecting.

More curious is why it stopped working before. The form declares `method="post"` however the button triggers a `GET` instead which of course isn't properly handled by spherocope

**Comment by mgttlinger** [comment]
Upon closer inspection, I notice that the `form` element around that button is "optimized" away by the browser. Hence the button triggers the action of the outer form instead.

**Comment by mgttlinger** [comment]
Funny that this ever worked as nested forms are not allowed in general...
