### ISSUE TITLE
Queries with deliberately "missing" slots

### ISSUE THREAD

**Issue by nfdykes** [ausgerechnet/spheroscope#62]
When testing the hierarchical queries function, I ran into some issues with queries where one of the expected slots is deliberately omitted (e.g. pattern3_ellipsis_hoping_concept, which assumes that the "wanter" is the author as in 'Hoping for successful outcome!').

Presumably due to queries like this, the hierarchical query function fails on the entire pattern:
 KeyError: "['match'] not in index"

- I assume that in the long run, we'll probably want to fill in these omitted slots with something by default. Not sure if it makes sense for spheroscope to handle this?
- Would it be (more) practical to de-select particular queries? That might generally be useful while everything's still so much in flux.
- It would be nice for debugging to have the error message specify which queries are causing problems.

**Comment by ausgerechnet** [comment]
- spheroscope ignores all matches of the base pattern that do not contain the respective slot
- the error here is actually a direct consequence of #63 and will be fixed in the same PR
- deselecting queries would add a bit of complexity, I would suggest to just not categorize queries that are unstable as belonging to the respective pattern
- the logger actually displays the query that is currently being run. re-directing logger output to the frontend might be a good idea though, I created a separate feature request: #68
